### ISSUE TITLE
Syntax highlighting not working on Sublime Text 4

### ISSUE THREAD

**Issue by juangiordana** [corneliusio/svelte-sublime#25] opened 2022-02-04 15:12 UTC
When opening .svelte files the in Sublime Text 4 the syntax highlighting is not being activated by default.

Looking at the console I see this message: `ignored packages updated to: ["Svelte", "Vintage"]`

**Comment by istudyatuni** [comment] 2022-02-07 16:06
This message appears when you disable/enable a package. Perhaps you have disabled it?

**Comment by corneliusio** [comment] 2022-02-09 14:46
@juangiordana

@istudyatuni is correct, you may have accidentally disabled it at some point. That said, I have some fixes I need to get released for ST4 which may also be causing this though I haven't seen it happen before. Regardless, there should be a new release for better ST4 compatibility soon.

**Comment by juangiordana** [comment] 2022-02-09 15:22
I tried this with an empty configuration before reporting the bug.

**Comment by juangiordana** [comment] 2022-03-04 17:15
This issue happened to me again this week. For some reason the plugin messes with the `ignored_packages` setting in Sublime Text 4. After correcting settings it worked as expected. This was a again a pristine setup I was working with.

**Comment by hellafont** [comment] 2022-03-20 10:17
I'm also seeing this issue in ST4 however my `ignored-packages` do not list Svelte

**Comment by corneliusio** [comment] 2022-04-01 15:30
Want to apologize for my absence on this project for the last few months. I've been extremely overloaded with my full-time work since the beginning of the year and it has made it impossible to address these issues in a timely manner. That said, things are leveling back out now and I will be addressing this and other issues in the next week or two.

Appreciate everyone's patients as I know how frustrating it can feel to be at the mercy of an open-source project that isn't keeping up with changes and fixes without any real recourse. This repo is not abandoned and I will absolutely be continuing to maintain it for the foreseeable future.

**Comment by corneliusio** [comment] 2022-04-17 15:28
Fixes for this have been deployed and can be accessed at https://github.com/corneliusio/svelte-sublime/releases/tag/st4-3.5.0 if you're interested in downloading manually.

Due to changes to the package control channel, I was forced to submit an update to them as well to handle releases for ST3 and ST4 respectively. https://github.com/wbond/package_control_channel/pull/8522
This will likely take a few days to be merged in, so in the meantime, the best way to get these updates is by manually installing from here.

I will leave this issue open for the time being for anyone to submit feedback in case they run into problems but will presume the issue is resolved once the package control channel has been updated.

**Closed as completed** 2022-05-05 14:52 UTC
