### ISSUE TITLE
Block level element names wouldn't accommodate slashes.

### ISSUE THREAD

**Issue by ehzro3** [corneliusio/svelte-sublime#21] opened 2021-12-11 05:45 UTC
I often see component names such as `<Header />`. But the slash is not welcome because `<header></header>` used to be a block-level element in HTML, I think it should be different in Svelte with PascalCased component names.
![Screen Shot 2021-12-11 at 14 40 20](https://user-images.githubusercontent.com/40330010/145665640-a55d3343-10b3-4b7b-90c6-7fde16b73700.png)
![Screen Shot 2021-12-11 at 14 37 13](https://user-images.githubusercontent.com/40330010/145665643-abd4d79d-82b1-4168-ac35-235d3886c4a4.png)

**Comment by corneliusio** [comment] 2022-04-01 15:29
Want to apologize for my absence on this project for the last few months. I've been extremely overloaded with my full-time work since the beginning of the year and it has made it impossible to address these issues in a timely manner. That said, things are leveling back out now and I will be addressing this and other issues in the next week or two.

Appreciate everyone's patients as I know how frustrating it can feel to be at the mercy of an open-source project that isn't keeping up with changes and fixes without any real recourse. This repo is not abandoned and I will absolutely be continuing to maintain it for the foreseeable future.

**Comment by ehzro3** [comment] 2022-04-02 22:44
I'm glad you are back @corneliusio !
I'm using this one all the time, I was worried about it being deprecated, and me having to build it from scratch.

**Comment by corneliusio** [comment] 2022-04-17 15:43
This ended up being a bit more straightforward than I was anticipating. Believe I have a fix for this implemented and you can test it out here: https://github.com/corneliusio/svelte-sublime/releases/tag/st4-3.5.1

Due to changes to the package control channel, I was forced to submit an update to them as well to handle releases for ST3 and ST4 respectively. https://github.com/wbond/package_control_channel/pull/8522
This will likely take a few days to be merged in, so in the meantime, the best way to get these updates is by manually installing from here.

If you'd like to download and test out the updated package manually that'd be great, otherwise, I will presume the issue is resolved once the package control channel has been updated.

**Closed as completed** 2022-05-05 14:52 UTC
Labels: enhancement
