### ISSUE TITLE
Syntax Highlighting is incorrect for blocks without quotes

### ISSUE THREAD

**Issue by jum-s** [corneliusio/svelte-sublime#26] opened 2022-02-14 15:43 UTC
first, thank you for this awesome package and all associated work.

here is the problem:

with optional quotes (correct highlight):
![2022-02-14_16-40](https://user-images.githubusercontent.com/5363918/153895915-0e954061-11d0-49eb-8b1b-8b43b16e2f65.png)

without quote
![2022-02-14_16-40_1](https://user-images.githubusercontent.com/5363918/153896062-b5ef55ca-7cda-44f0-b961-31f2bd237ffd.png)

config:
Sublime Text Build 4126

**Comment by corneliusio** [comment] 2022-04-01 15:30
Want to apologize for my absence on this project for the last few months. I've been extremely overloaded with my full-time work since the beginning of the year and it has made it impossible to address these issues in a timely manner. That said, things are leveling back out now and I will be addressing this and other issues in the next week or two.

Appreciate everyone's patients as I know how frustrating it can feel to be at the mercy of an open-source project that isn't keeping up with changes and fixes without any real recourse. This repo is not abandoned and I will absolutely be continuing to maintain it for the foreseeable future.

**Comment by corneliusio** [comment] 2022-04-17 15:27
Fixes for this have been deployed and can be accessed at https://github.com/corneliusio/svelte-sublime/releases/tag/st4-3.5.0 if you're interested in downloading manually.

Due to changes to the package control channel, I was forced to submit an update to them as well to handle releases for ST3 and ST4 respectively. https://github.com/wbond/package_control_channel/pull/8522
This will likely take a few days to be merged in, so in the meantime, the best way to get these updates is by manually installing from here.

I will leave this issue open for the time being for anyone to submit feedback in case they run into problems but will presume the issue is resolved once the package control channel has been updated.

**Comment by jum-s** [comment] 2022-04-24 07:45
setting "Svelte" as file type (previously HTML) fixed my issue.
Thanks for the time you put into that

**Comment by corneliusio** [comment] 2022-04-27 15:29
@jum-s Yes! Files with a `.svelte` extension (or .svlt because I used to do that way back before there was a standard) should automatically use this syntax def. Otherwise, if you're using `.html` files, you need to set that manually in Sublime. Note that you can also set default syntaxes for various file types in Sublime under **View** > **Syntax** > **Open all with current extension as…** and choosing the desired syntax definition.

**Closed as completed by corneliusio** 2022-04-27 15:29 UTC
