### ISSUE TITLE
Syntax Highlighting Not Applied Correctly

### ISSUE THREAD

**Issue by lubiah** [corneliusio/svelte-sublime#20] opened 2021-10-31 04:25 UTC
After updating my sublime text, am beginning to nice this error
![Capture](https://user-images.githubusercontent.com/63173187/139567581-32f1396d-9190-4def-9794-6f529ee5aeb5.PNG)

**Comment by corneliusio** [comment] 2021-11-01 14:41
@kudadam I'm not able to replicate this exact issue at the moment. I'm assuming you're on Sublime Text 4, could you let me know exactly what build number you're on as well as what OS your using?

Also noting, I'm currently still working through a few issues from the ST4 update after the most recent fix for all the embed scopes being broken with the new version of Sublime.

**Comment by lubiah** [comment] 2021-11-01 14:43
Yeah, am on Sublime text 4 build 4113.
OS is Win 8.

**Comment by corneliusio** [comment] 2022-04-01 15:29
Want to apologize for my absence on this project for the last few months. I've been extremely overloaded with my full-time work since the beginning of the year and it has made it impossible to address these issues in a timely manner. That said, things are leveling back out now and I will be addressing this and other issues in the next week or two.

Appreciate everyone's patients as I know how frustrating it can feel to be at the mercy of an open-source project that isn't keeping up with changes and fixes without any real recourse. This repo is not abandoned and I will absolutely be continuing to maintain it for the foreseeable future.

**Comment by corneliusio** [comment] 2022-04-17 15:29
Fixes for this have been deployed and can be accessed at https://github.com/corneliusio/svelte-sublime/releases/tag/st4-3.5.0 if you're interested in downloading manually.

Due to changes to the package control channel, I was forced to submit an update to them as well to handle releases for ST3 and ST4 respectively. https://github.com/wbond/package_control_channel/pull/8522
This will likely take a few days to be merged in, so in the meantime, the best way to get these updates is by manually installing from here.

I will leave this issue open for the time being for anyone to submit feedback in case they run into problems but will presume the issue is resolved once the package control channel has been updated.

**Closed as completed** 2022-04-17 18:26 UTC
